### ISSUE TITLE
error happened while reading a single line comment

### ISSUE THREAD

**Issue by belf** [fholm/IronJS#33]
in Debug.Console paste the following snippet:

``` javascript
// aaaa\bb\cc\dd\utils.js
function a( ) {}
a()


the error is:
IronJS.Error+CompileError: Invalid hex digit 't'
On line 2, column 19 in <unknown>
1: 
2: // aaaa\bb\cc\dd\utils.js
---------------------^

   at IronJS.Error.CompileError.Raise[a](String msg, Tuple`2 pos, String source, String path) in IronJS\Src\IronJS\Error.fs:line 93
   at IronJS.Compiler.Lexer.Input.error[a](T t, String msg) in IronJS\Src\IronJS\Compiler.Lexer.fs:line 437
   at IronJS.Compiler.Lexer.readUnicodeEscape(T s) in IronJS\Src\IronJS\Compiler.Lexer.fs:line 526
   at IronJS.Compiler.Lexer.singlelineComment(T s) in IronJS\Src\IronJS\Compiler.Lexer.fs:line 663
   at IronJS.Compiler.Lexer.lexer@954(T s, Unit unitVar0) in IronJS\Src\IronJS\Compiler.Lexer.fs:line 985
   at IronJS.Compiler.Parser.consume(State p) in IronJS\Src\IronJS\Compiler.Parser.fs:line 255
   at IronJS.Compiler.Parser.nullStmt@462-1.Invoke(State p) in IronJS\Src\IronJS\Compiler.Parser.fs:line 462
   at IronJS.Compiler.Parser.statementList(State p) in IronJS\Src\IronJS\Compiler.Parser.fs:line 381
   at IronJS.Compiler.Parser.parse(String source, Environment env) in IronJS\Src\IronJS\Compiler.Parser.fs:line 1399
   at IronJS.Hosting.FSharp.compile(String source, T t) in IronJS\Src\IronJS\Hosting.fs:line 152
   at IronJS.Hosting.CSharp.Context.Execute(String source) in IronJS\Src\IronJS\Hosting.fs:line 224
   at DebugConsole.MainWindow.<>c__DisplayClass27.<runSources>b__1f() in IronJS\Src\Tools\DebugConsole\MainWindow.xaml.cs:line 385
```

**Comment by ChaosPandion** [comment]
> In string literals, regular expression literals, and identifiers, any character (code unit) may also be expressed 
> as a Unicode escape sequence consisting of six characters, namely \u plus four hexadecimal digits. Within a 
> comment, such an escape sequence is effectively ignored as part of the comment.

To me this implies that a Unicode escape sequence should not be parsed as we see in the source code. Any thoughts?

**Comment by otac0n** [comment]
That is correct.  This is indeed a bug.
